# filepath: market-research-platform/backend/models/trend.py
# ORM model for identified market trends.
# Trends are generated by the trend analysis engine and stored here
# so the dashboard can display them without re-running the LLM query.

from datetime import datetime
from sqlalchemy import String, DateTime, Float, JSON, Text
from sqlalchemy.orm import Mapped, mapped_column
from database import Base


class Trend(Base):
    __tablename__ = "trends"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    confidence_score: Mapped[float] = mapped_column(
        Float, nullable=True
    )  # 0.0 – 1.0: how strongly supported across sources
    supporting_chunk_ids: Mapped[list] = mapped_column(
        JSON, default=list
    )  # LlamaIndex node IDs for provenance
    source_document_ids: Mapped[list] = mapped_column(
        JSON, default=list
    )  # Document.id values this trend was derived from
    identified_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
    tags: Mapped[list] = mapped_column(
        JSON, default=list
    )  # e.g. ["AI", "logistics", "supply chain"]

    # TODO: Add is_active field (False = archived trend)
    # TODO: Add industry_vertical field for filtering

    def __repr__(self) -> str:
        return f"<Trend id={self.id} title={self.title!r} score={self.confidence_score}>"
